Repository moevm/mse1h2025-ripes, pull requests merged in 2025-05, with the labels that each got.

#62 [ADD] Classes for testing students programs and task exmple
  docker/server.dockerfile
  moodle/server/app.py
  moodle/server/tester/all_tasks.py
  moodle/server/tester/ripes_tester.py
  moodle/server/tester/task.py
  moodle/server/tester/task1.py
Labels: backend, feature, high priority

#68 Integration and functional testing
  .github/workflows/compose.yml
  moodle/tests/__init__.py
  moodle/tests/requirements.txt
  moodle/tests/test_page.py
Labels: frontend, backend, feature, moderate priority, docker

#69 [UPD] add advanced tasks
  moodle/server/tester/all_tasks.py
  moodle/server/tester/task2.py
  moodle/server/tester/task3.py
  moodle/server/tester/task4.py
Labels: enhancement

#72 [ADD] add documentation
  docker/.env.example
  reports.md
  reports/report_3.pdf
  reports/start.md
  reports/task_create.md
Labels: documentation

#80 Feat/statistic page
  docker/init.sql
  moodle/server/app.py
  moodle/server/static/statistic.js
  moodle/server/templates/index.html
  moodle/server/templates/statistics.html
Labels: frontend, backend, DB, feature, high priority

#82 [UPD] index page remake
  docker/server.dockerfile
  moodle/server/static/handlers.js
  moodle/server/static/styles.css
  moodle/server/templates/index.html
  moodle/server/templates/statistics.html
Labels: frontend, feature, high priority

#95 [FIX] Fix image name
  reports/start.md
Labels: documentation, fix

#96 [FIX] Eternal check due to ecall with unknown command
  moodle/server/tester/ripes_tester.py
Labels: backend, fix, high priority

#100 Feature/display task info
  moodle/server/app.py
  moodle/server/templates/index.html
  moodle/server/tester/all_tasks.py
  moodle/server/tester/task.py
  moodle/server/tester/task1.py
  moodle/server/tester/task2.py
  moodle/server/tester/task3.py
  moodle/server/tester/task4.py
Labels: enhancement, frontend, backend, feature, moderate priority

#102 [FIX] fix grammar mistake and testing time
  moodle/server/tester/ripes_tester.py
Labels: bug, fix, moderate priority, refactoring

#103 Added seeded generation
  docker/init.sql
  moodle/server/app.py
  moodle/server/tester/task.py
  moodle/server/tester/task1.py
  moodle/server/tester/task2.py
  moodle/server/tester/task3.py
  moodle/server/tester/task4.py
Labels: backend, DB, feature, moderate priority

#105 [REF] change task 0 name
  moodle/server/tester/task.py
Labels: fix, refactoring
